name: Merge dev to main

on:
  push:
    branches:
      - dev

jobs:

  merge-dev-to-main:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

      - name: Switch to main branch
        run: |
          git checkout main

      - name: Merge dev into main
        run: |
          git merge origin/dev --no-edit

      - name: Push changes to main
        run: |
          git push origin main
