name: Dev branch manual triggers

on:
    push:
    workflow_dispatch:

jobs:
    Dev-branches-manually-triggering:

        runs-on: ubuntu-latest

        steps:
            - name: Linux commands
              run: date