name: Second yaml from dev branch

on:
  push:
    branches:
      - dev

  workflow_dispatch:

jobs:
  second-job-dev:

    runs-on: ubuntu-latest

    steps:

      - name: Create a filename
        run: echo "My name is Dhage Anil Kumar and Im learning GitHub Actions" > anil.txt

      - name: Display the filename
        run: cat anil.txt