name: Create a file and Display them

on: push

jobs:
    files:

        runs-on: ubuntu-latest

        steps:

            - name: Create a file anil.txt
              run: echo "My name is Dhage Anil Kumar" > anil.txt

            - name: Display the file
              run: cat anil.txt

            - name: Show me the path
              run: pwd, ls -lrth

            - name: Show me the all files
              run: ls -lrth

            - name: Show me the date
              run: 
                echo "Todays date is:"
                date