name: create a file name

on: push

jobs:
    fileName:

        runs-on: ubuntu-latest

        steps:
            - name: Create a file
              run: echo "My Name is Dhage Anil Kumar and im leanring Github Actions" > kumar.txt
              
            - name: Display the file
              run: ls -lrth

            - name: Display the path
              run: pwd

            - name: Display the date
              run: date