name: Checking for another one Github Actions

on: push

jobs:
    test-job:
        runs-on: ubuntu-latest

        steps:
            - name: "Display the my name"
              run: echo "My name is Dhage Anil Kumar"

            - name: Display today's date
              run: |
                echo "Today's date is:"
                date